version: "3.6"

services:
  github-issue-schedule:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: github-issue-schedule
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CONFIG_FILE=/appbin/config.yaml
    volumes:
      - ../assets/config.yaml:/appbin/config.yaml
