buffer_window_days: 7
projects:
  - name: Hyperledger Bevel
    github_org: hyperledger
    github_repo: bevel
    maintainers:
      - arsulegai
    schedules:
      - date: 2023-05-12
        title: Submit the 2023 Q3 quarterly report
        description: Dear Bevel maintainers, please submit the 2023 Q3 report.
